name: EAS Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-build:
    name: Android EAS Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS Login
        run: |
          cd app
          eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build Android
        run: |
          cd app
          eas build -p android --profile production --non-interactive

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            ./app/build
