name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        working-directory: Server  # 👈 all npm commands run inside /Server

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: Server/package-lock.json  # 👈 correct case-sensitive path

      - name: Install dependencies
        run: npm ci

      - name: Restart project
        run: pm2 restart door

      # - name: Run tests
      #   run: npm test
